version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '9606:80'
        volumes:
            - ./app:/var/www/html

    db:
        image: 'mysql'
        restart: always
        environment:
            MYSQL_DATABASE: blogmvc
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./database/blogmvc.sql:/docker-entrypoint-initdb.d/blogmvc.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1